# spring.application.name=prediction
spring:
  application:
    name : prediction
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      # dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: 
    password: 
  

server:
  port: 3005
jwt:
  secret: ${JWT_PASSWORD}
token:
  accessTokenExpiry: 900000
  refreshTokenExpiry: 5184000000
